### ISSUE TITLE
[issue] Could not initialize interactsh client when running nuclei

### ISSUE THREAD

**Issue by khanh-cm** [projectdiscovery/nuclei#1023]
**Describe the bug**
My nuclei work well in version 2.5.0 however, when I updated to the new version 2.5.1, I got the error **Could not initialize interactsh client: could not create client: could not make register request**, how can I fixed this issue, my command when running nuclei is:
**nuclei -l urls.txt -t nuclei-templates/ -o output.txt**

**Nuclei version**
2.5.1

**Screenshot of the error or bug**
![image](https://user-images.githubusercontent.com/48460056/133358438-925dbb4b-19f8-4f73-9cc5-4d8472d0de9b.png)

**Comment by ehsandeep** [comment]
Thanks for reporting @khanh-cm, This is now fixed in the dev version with https://github.com/projectdiscovery/nuclei/commit/259ccb118ffb38c1a6c891c96d80da2a389f8716

**Comment by leorac** [comment]
@ehsandeep when it will be released?

**Comment by ehsandeep** [comment]
@leorac we just pushed a new release including fix.

**Comment by aitor-arronte** [comment]
> @leorac we just pushed a new release including fix.

I am still experiencing the same issue in 2.5.6 and 2.5.6-dev [ERR] Could not initialize interactsh client: could not create client: could not make register request: POST https://interact.sh/register giving up after 6 attempts: Post "https://interact.sh/register": context deadline exceeded (Client.Timeout exceeded while awaiting headers). 

Is there a specific version that should be used? --Thanks

**Comment by kr0t3** [comment]
still have same issue

**Comment by melvinvarkey** [comment]
I am also facing the same issue. Looks like the Interactsh.com url is down and nuclei is not able to register properly.

**Comment by SNISS** [comment]
I am also

**Comment by josephmiller2000** [comment]
@ehsandeep Well still the same issue here

![Snap_Shot_02867](https://user-images.githubusercontent.com/24210340/147866889-8f24ac08-17f1-4e83-afbd-c37a33c5486c.png)

**Comment by aitor-arronte** [comment]
Seems like this error happens intermittently, due probably to the server experiencing down time or overly saturated. I have been able to run tests in the last couple of weeks. Just in case it can help someone else.

**Comment by AjCaroline** [comment]
Same issue happening version 2.5.7 and not intermittent, but every time I run the tool.

**Comment by ehsandeep** [comment]
@AjCaroline try updating to the latest version of the project, i.e [v2.7.1](https://github.com/projectdiscovery/nuclei/releases/tag/v2.7.1)

**Comment by NotScortator** [comment]
still have this problem on v2.7.7 anyone know of a fix rather than just disabling it via -ni

**Comment by rasoul2023** [comment]
error in version 2.8.1: 

`[ERR] Could not initialize interactsh client: could not create client: could not register to servers: could not make register request: POST https://oast.fun/register giving up after 1 attempts: Post "https://oast.fun/register": dial tcp 206.189.156.69:443: i/o timeout
`

**Comment by Rameshkanna2k** [comment]
> error in version 2.8.1:
> 
> [INF] Using Nuclei Engine 2.8.1 (latest) [INF] Using Nuclei Templates 9.3.1 (latest) [INF] Templates added in last update: 2 [INF] Templates loaded for scan: 1513 [INF] Targets loaded for scan: 1 [INF] Templates clustered: 16 (Reduced 10 HTTP Requests)
> 
> `[ERR] Could not initialize interactsh client: could not create client: could not register to servers: could not make register request: POST https://oast.fun/register giving up after 1 attempts: Post "https://oast.fun/register": dial tcp 206.189.156.69:443: i/o timeout `

Have u got solution on this problem?

**Comment by Harshil00** [comment]
You should run  the nuclei with root privs. 

etc. sudo nuclei -l target.txt -t ~/nuclei-templates/xxxx

**Comment by anjidany** [comment]
use 
sudo nuclei -i urls -t cves/
