### ISSUE TITLE
Custom header is silently truncated

### ISSUE THREAD

**Issue by gano3s** [projectdiscovery/nuclei#2066]
I am using a custom header (User-Agent) set to the value 
```
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; RedMi Note 5 Build/RB3N5C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36 
```
Starting with version 2.6.6, the used user-agent is truncated to
```
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; RedMi Note 5 Build/RB3N5C; wv) AppleWebKit/537.36 (KHTML
```

I discovered it, because our internal alerts were suppressed when this UA was used. 
Since the used value is a valid, used also by the mobile phones, I believe that nuclei should support it.

I believe, that this behavior was introduced in this PR (when I revert these changes, it works as expected). https://github.com/projectdiscovery/nuclei/pull/1756/files

### Nuclei version:
started in 2.6.6 

### Steps To Reproduce:
use long custom header

**Comment by ehsandeep** [comment]
Thanks for reporting this @gano3s, this is now fixed in dev branch of the project with https://github.com/projectdiscovery/nuclei/pull/2133

**Comment by NotoriousRebel** [comment]
Not a fan of creating a new issue when this already exists but @gano3s this is still broken...
Within the dev branch as well, if you do `-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"`, this is what the User-Agent will be: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML` it's silently removing everything after the first `,`. Removing the `,` fixes it but is not an ideal solution.

**Comment by ehsandeep** [comment]
@NotoriousRebel this is now fixed in the `dev` version.
