### ISSUE TITLE
Unusual Memory Usage in the Latest Version of Nuclei: 

### ISSUE THREAD

**Issue by aravindb26** [projectdiscovery/nuclei#3746]
The memory usage of the latest version of Nuclei seems unusually high, consuming 8 GB per minute. After running for 10 minutes, it reached a significant memory usage of 80 GB. Concerned about this excessive consumption, I decided to manually terminate the process. It may be worth investigating further or reaching out to the developers for clarification on this memory usage pattern.

**Comment by ehsandeep** [comment]
@aravindb26 this is known and fixed in dev branch of nuclei, new release will be out soon, closing as duplicate issue of https://github.com/projectdiscovery/nuclei/issues/3666

**Comment by ehsandeep** [comment]
@aravindb26 this is now fixed in latest release of nuclei i.e [v2.9.5](https://github.com/projectdiscovery/nuclei/releases/tag/v2.9.5)

**Comment by Silur** [comment]
still present in 2.9.13, scans just hangs untill eventually consumes all of RAM and Swap and die

**Comment by yanjiache** [comment]
This problem seems to still exist in version 3.1.0.
User-defined POC file is added, and it reaches a certain stage during operation, and the memory consumption is abnormal.
![nuclei](https://github.com/projectdiscovery/nuclei/assets/73382341/3515a7ef-16c5-4e17-84cf-0c391220ff3a)
Finally, the memory is full and the program crashes.
![nuclei2](https://github.com/projectdiscovery/nuclei/assets/73382341/f45c7242-80e3-43e3-9703-fdcc7b96e4b9)

**Comment by yanjiache** [comment]
This problem will not occur when using the original poc of nuclei.
