### ISSUE TITLE
Nuclei Error Code 137

### ISSUE THREAD

**Issue by rxerium** [projectdiscovery/nuclei#4530]
### Nuclei version:
3.1.2

### Current Behavior:
I am running Nuclei scans through Docker however I keep receiving error code 137 which means the system has ran out of resources, particularly RAM. I never used to encounter this issue when running scans and not sure why this is occurring. The same issue occurs when running Nuclei from source. 

### Expected Behavior:
Nuclei should run and complete the scan

### Steps To Reproduce:
Below is the docker command I use:
`sudo docker run -v /home/ubuntu:/files projectdiscovery/nuclei -l /files/input.txt -config /files/nuclei-config.yaml -o /files/output.json`

### Anything else:
Below are my server specs in which I am running the latest nuclei docker image on:
- 4GB RAM
- 2vCPU cores
- 80GB SSD
- OS: Ubuntu 23.04
---
My config file:
```
tags: kev
etags: intrusive
scan-strategy: host-spray
concurrency: 100
bulk-size: 10
max-host-error: 10
max-redirects: 1
stream: true
stats: true
ts: true
jsonl: true
```
---
Notes:
- The input list has 41k hosts, I have reduced this to 10k hosts and still encounter the same issue. 
- I have not set any memory restrictions on the server or through the docker command
- Nothing else is running (other than system processes) on the server except docker/nuclei
- I have adjusted the concurrency/bulk size to 200/50 then 50/5. I have also ran scans without the `stream` tag.

**Comment by rxerium** [comment]
Note: I have this working on version 2.9.15. So something in a later release is causing this issue.

**Comment by tarunKoyalwar** [comment]
@rxerium ,  i am tracking possible cause of this memory  leak at https://github.com/projectdiscovery/nuclei/issues/4629 . based on profiles contributed by @mastercho in https://github.com/projectdiscovery/nuclei/issues/4552 .

meanwhile can you share more info to help with finding and fixing this bug

> are you using any custom templates ?
> if not , can you share what public templates you are using (just share filters or templates dir/path that you are running )
> approx time after which nuclei is killed ? 

finally can you share last 10 cpu and memory profiles by running nuclei in profiling mode using

```
$ export PPROF_TIME=30s
$ PPROF=1 nuclei -l alive.txt -stats -o res.txt -c 100  |& tee log.txt     
```

> pls adjust PPROF_TIME based on total runtime , i.e if nuclei exists too early reduce PPROF_TIME to 5s-10s

**Comment by tarunKoyalwar** [comment]
@rxerium , i have pushed a potential fix for this at #4630 , can you try running from that branch or by directly installing from this commit hash

> ```
> $ go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@064ac7a
> ```
> 
> just make sure nuclei version shown in command is `nuclei-v3.1.6-dev`
> 
> ```
> $  nuclei -version
> [INF] Nuclei Engine Version: v3.1.6-dev
> ```
> 
> let me know if this resolves this issue or affect any template

**Comment by rxerium** [comment]
Hi @tarunKoyalwar, thanks for pushing this fix. I am running workflows through Docker, have you made the patch available through docker?

Also, do we know when this will be released to production?

**Comment by rxerium** [comment]
Hi @tarunKoyalwar, hope all is well with you. I've tested a few scans using v3.1.6 however I still encounter the same issue. Would you like me to provide the memory profiles mentioned above? Thanks

**Comment by tarunKoyalwar** [comment]
@rxerium , that would be helpful also can you upload in this issue/discussion https://github.com/projectdiscovery/nuclei/issues/4552#issuecomment-1906181956 . we have kept that issue open since crash it not completely fixed

**Comment by rxerium** [comment]
Just looking into memory profiles now and as I am running scans using Docker I don't believe it is possible to however do let me know if there is an alternative way of achieving this

**Comment by rxerium** [comment]
Hey @tarunKoyalwar, I saw the article recently published [here](https://docs.projectdiscovery.io/tools/nuclei/mass-scanning-cli) in regards to mass scanning. I am using the following config but still encounter a memory issue:
```
scan-strategy: host-spray
concurrency: 10
bulk-size: 10
max-host-error: 10
max-redirects: 1
rps: 50

```

Do let me know if I should adjust any of the above based on  your recommendations. My input list contains 6000-8000 hosts and I'm using ~350 templates for scans. 

Thanks
