### ISSUE TITLE
[issue] Duplication of connection header

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#503]
### Replicate:- 

When the template has a connection header defined in the template + nuclei add its own.

**Comment by Ice3man543** [comment]
This is fixed in the latest dev branch!

**Comment by Saikuron** [comment]
I created the issue #890 because this problem is still there, but it just doesn't show up with the native -debug option. However, the header is still duplicated
