### ISSUE TITLE
Issue with template update using custom location

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#964]
**Describe the bug**

Reported by @dwisiswant0

As default, nuclei downloads template under `$HOME/nuclei-templates` folder, with an option for users to define a custom location for installing templates using `ud` flag, the issue with using custom location is, it's always gets overwritten by default install location.

**Nuclei version**

v2.4.3

**Screenshot of the error or bug**

```sh
nuclei -ut -ud test

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.4.3

		projectdiscovery.io

[INF] nuclei-templates are not installed, installing...
[INF] Successfully downloaded nuclei-templates (v8.4.5). GoodLuck!

$cat ~/.config/nuclei/.templates-config.json | jq .

{
  "templates-directory": "test",
  "current-version": "8.4.5",
  "last-checked": "2021-08-22T01:02:10.649348+05:30",
  "ignore-url": "https://raw.githubusercontent.com/projectdiscovery/nuclei-templates/master/.nuclei-ignore",
  "nuclei-version": "2.4.3",
  "last-checked-ignore": "2021-08-22T01:02:10.649348+05:30",
  "nuclei-latest-version": "2.4.3",
  "nuclei-templates-latest-version": "8.4.5"
}

$nuclei

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.4.3

		projectdiscovery.io

[INF] nuclei-templates are not installed, installing...
[INF] Successfully downloaded nuclei-templates (v8.4.5). GoodLuck!
[INF] Using Nuclei Engine 2.4.3 (latest)
[INF] Using Nuclei Templates 8.4.5 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates loaded: 1772 (New: 1869)
[INF] No results found. Better luck next time!

$cat ~/.config/nuclei/.templates-config.json | jq .

{
  "templates-directory": "/Users/sandeep/nuclei-templates",
  "current-version": "8.4.5",
  "last-checked": "2021-08-22T01:03:09.610453+05:30",
  "ignore-url": "https://raw.githubusercontent.com/projectdiscovery/nuclei-templates/master/.nuclei-ignore",
  "nuclei-version": "2.4.3",
  "last-checked-ignore": "0001-01-01T00:00:00Z",
  "nuclei-latest-version": "2.4.3",
  "nuclei-templates-latest-version": "8.4.5"
}
```

## Expected Behaviour:

User specified custom location should be respected for further manual and automatic updates.

**Comment by Ice3man543** [comment]
This is fixed by https://github.com/projectdiscovery/nuclei/commit/fb2ec8f5d262ddf74d766509163655038a0fa222. 

```
./nuclei -ut -ud test -v                        

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.4.4-dev

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[VER] Downloading nuclei-templates (v8.4.6) to /Users/ice3man/projectdiscovery/nuclei/v2/cmd/nuclei/test

Nuclei Templates v8.4.6 Changelog
+-------+-------+---------+
| TOTAL | ADDED | REMOVED |
+-------+-------+---------+
|  1939 |     0 |       0 |
+-------+-------+---------+
[INF] Successfully downloaded nuclei-templates (v8.4.6). GoodLuck!
 ./nuclei                

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.4.4-dev

                projectdiscovery.io

[INF] Using Nuclei Engine 2.4.4-dev (development)
[INF] Using Nuclei Templates 8.4.6 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates loaded: 1839 (New: 0)
[INF] No results found. Better luck next time!
```

**Comment by MushR00m** [comment]
The issue is not solved?

Nuclei version
v2.6.2

```
# nuclei -ud .config/nuclei/nuclei-templates/
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.2

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[INF] Successfully downloaded nuclei-templates (v8.8.5) to /root/.config/nuclei/nuclei-templates. GoodLuck!
[INF] Using Nuclei Engine 2.6.2 (latest)
[INF] Using Nuclei Templates 8.8.5 (latest)
[INF] Templates added in last update: 94
[INF] Templates loaded for scan: 2909
[INF] No results found. Better luck next time!

# cat .templates-config.json
{
  "nuclei-templates-directory": "/root/.config/nuclei/nuclei-templates",
  "nuclei-templates-version": "8.8.5",
  "nuclei-version": "2.6.2",
  "nuclei-ignore-hash": "3c0ad5eb37d6d2da8efd55375b9d0432",
  "nuclei-latest-version": "2.6.2",
  "nuclei-templates-latest-version": "8.8.5"
}
```
run again nuclei

```
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.2

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[INF] Successfully downloaded nuclei-templates (v8.8.5) to /root/nuclei-templates. GoodLuck!
[INF] Using Nuclei Engine 2.6.2 (latest)
[INF] Using Nuclei Templates 8.8.5 (latest)
[INF] Templates added in last update: 94
[INF] Templates loaded for scan: 2909
[INF] No results found. Better luck next time!
```

```
cat .templates-config.json
{
  "nuclei-templates-directory": "/root/nuclei-templates",
  "nuclei-templates-version": "8.8.5",
  "nuclei-version": "2.6.2",
  "nuclei-ignore-hash": "3c0ad5eb37d6d2da8efd55375b9d0432",
  "nuclei-latest-version": "2.6.2",
  "nuclei-templates-latest-version": "8.8.5"
}
```

**Comment by ehsandeep** [comment]
@MushR00m this is being tracked here - https://github.com/projectdiscovery/nuclei/issues/1611
